#!/bin/sh

function get_pipeline() {
   export SEQ_PRISMS_BIN=/dataset/gseq_processing/active/bin/wgs_prism/seq_prisms
   export WGS_PRISM_BIN=/home/perrybe/wgs_prism2
   cd $WGS_PRISM_BIN
   wgs_version=$1

   echo "preparing to run wgs qc pipeline version $wgs_version (press enter to continue)"
   read answer
   is_alpha=`echo $wgs_version | grep alpha`
   if [ ! $is_alpha ]; then 
      git checkout -q $wgs_version 
      if [ $? != 0 ]; then
         echo "unable to checkout pipeline version $wgs_version"
         exit 1
      fi
      exec ./_run_wgs_qc -i $wgs_version 
   else
      echo "(no checkout for alpha versions, just running in current branch)"
      exec ./_run_wgs_qc -i $wgs_version 
   fi
}

get_pipeline 2.0.0
