# Based on: https://github.com/jdblischak/smk-simple-slurm
# Default slurm profile for running the pipeline on the eRI
cluster:
  mkdir -p {config[OUT_ROOT]}/logs/slurm &&
  sbatch
    --account={resources.account}
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem="{resources.mem_gb}G"
    --job-name=smk-{rule}-{wildcards}
    --time={resources.time}
    --output={config[OUT_ROOT]}/logs/slurm/{rule}-{wildcards}-%j.out
    --parsable
default-resources:
  - account="2023_sequence_production"
  - partition=compute
  - time=120
  - mem_gb=48
restart-times: 3
local-cores: 2
latency-wait: 6000
jobs: 150
max-jobs-per-second: 0.5
keep-going: True
rerun-incomplete: True
printshellcmds: False
scheduler: greedy
use-conda: True
use-singularity: True
#singularity-args: "--bind /mnt/gpfs/persist/legacy_datasets"
reason: True
conda-frontend: conda
rerun-trigger: mtime
cluster-status: workflow/scripts/status.py
cluster-cancel: scancel
